# Generated by Django 3.1.3 on 2020-11-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('designer', models.CharField(max_length=50)),
                ('year_realeased', models.IntegerField()),
                ('number_of_players', models.IntegerField()),
                ('time_to_play', models.DurationField()),
                ('age_recommendation', models.IntegerField()),
            ],
        ),
    ]
