# Generated by Django 3.1.3 on 2020-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0004_pics_player_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
