# Generated by Django 3.1.3 on 2020-11-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0005_auto_20201104_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_to_play',
            field=models.IntegerField(),
        ),
    ]
